cluster_settings:
  path_to_logs: 
    # list all paths to logs that you use in this cluster. A path specified below should match a node's log directory at least once
    - /var/log/cassandra
  path_to_configs: 
    # list all paths to configs that you use in this cluster. A path specified below should match a node's log directory at least once
    - /etc/dse/cassandra/

  # one of: "dse", "cassandra" (only supporting those for now, and maybe that's enough)
  # TODO can get using nodetool like is done in TableAnalyzer/cfstats.receive.py#42, `nodetool version`
  cassandra_distribution: dse

  # set cluster defaults for node settings. Will be overwritten for a given node if set under settings_by_node
  node_defaults:
    # which jmx port to use (will use with -p flag for nodetool)
    JMX_PORT: 7199
    # can set which command to use for nodetool that will be default for whole cluster. Default is `nodetool` (ie package installation)
    nodetool_cmd: nodetool

settings_by_node:
  # settings specific to a certain node
  127.0.0.1:
    JMX_PORT: 7100
    nodetool_cmd: ~/lib/cassandra/bin/nodetool
