### used by table snap to monitor and back up files to AWS-S3
cassandra_data_file_directories: ["/var/lib/cassandra/data"]

cassandra_ops_os_user: cassandra
cassandra_shell_user: cassandra
cassandra_shell_password: cassandra
nodetool_exec: /bin/nodetool
cqlsh_exec: /bin/cqlsh
cassandra_env_exec: /etc/dse/cassandra/cassandra-env.sh
tools_install_folder: /usr/share/dse
cassandra_install_lib_folder: /usr/share/dse/cassandra/lib

cassandra_restart_command: systemctl restart dse

install_tablesnap: False
install_cassandra_exporter: False
install_filebeat: False
enable_jmx: False
create_reaper_db: False
