version: "3"
services:
  dse:
    image: datastax/dse-server:6.8.0
    command: [-k] # Run with Analytics capabilities enabled
##    command: [-s -k] # Run with Search and Analytics capabilities enabled
    environment:
      DS_LICENSE: accept # Accept licence on start
      JVM_EXTRA_OPTS: -Xms2g -Xmx2g
    cap_add:
      - IPC_LOCK # Allow DSE to lock memory with mlock
    ulimits:
      memlock: -1 # Lock memory
###    volumes:
###      - ./data/cassandra:/var/lib/cassandra
###      - ./data/spark:/var/lib/spark
###      - ./data/dsefs:/var/lib/dsefs
###      - ./data/cassandra:/var/log/cassandra
###      - ./data/spark:/var/log/spark
    ports:
      - "4040:4040"
      - "7080:7080"
      - "7081:7081"
      - "8983:8983"
      - "9042:9042"
      - "9077:9077"
      - "10000:10000"
