---
- name: create cassandra_exporter folder
  file:
    path: "{{ tools_install_folder }}/cassandra_exporter"
    state: directory
    mode: '0700'
    group: "{{ cassandra_ops_os_user }}"
    owner: "{{ cassandra_ops_os_user }}"

- name: download cassandra_exporter standalone
  get_url:
    url: "{{ cassandra_exporter_url }}"
    dest: "{{ tools_install_folder }}/cassandra_exporter"
    mode: '0440'
    group: "{{ cassandra_ops_os_user }}"
    owner: "{{ cassandra_ops_os_user }}"
  tags: ["exporter"]

- name: deploy cassandra_exporter config.yml
  template:
    src: "config.yml"
    dest: "{{ tools_install_folder }}/cassandra_exporter/cassandra_exporter-config.yml"
    mode: 0644
  tags: ["exporter"]

- name: install systemd cassandra_exporter.service unit
  template:
    src: "{{ item }}.j2"
    dest: "/etc/systemd/system/{{ item }}"
    mode: 0644
  with_items:
    - cassandra_exporter.service
  tags: ["exporter"]

- name: enable and start cassandra_exporter systemd service
  systemd:
    name: cassandra_exporter.service
    daemon_reload: yes
    enabled: yes
    state: restarted
  tags: ["exporter"]
